### ISSUE TITLE
Pretrained model or dataset?

### ISSUE THREAD

**Issue by kairess** [ryanhalabi/starcraft_super_resolution#5]
Hello, I really appreciate for sharing great work.

Can you share the pretrained model or training dataset?

It could be helpful!

**Comment by ryanhalabi** [comment]
The dataset used to generate the readme gif's is created dynamically when you kick off training at https://github.com/ryanhalabi/starcraft_super_resolution/blob/1bd7b0ba8612474892766b6d5dff32a38c81ca37/run.py#L90

I've uploaded the net that was used to generate the readme gifs here  https://github.com/ryanhalabi/starcraft_super_resolution/blob/master/upres/data/output/a_non_relu_units_%5B'128%2C9'%2C%20'256%2C1'%2C%20'19'%5D/models/a_non_relu_units_%5B'128%2C9'%2C%20'256%2C1'%2C%20'19'%5D_6400.hdf5

To use it you just need to supply the same name and layer specs to the `run.py` command and it should load automatically.


The above dataset is quite small, but if your looking for a larger dataset I had a screenshot generator to make a much larger dataset from a Flash VOD https://github.com/ryanhalabi/starcraft_super_resolution/blob/master/upres/utils/screenshot_generator.py 

However, I wasn't able to generate as good of results for the VOD images as for the smaller dataset.

**Comment by kairess** [comment]
Thanks a lot! I'll try that.
